<InfoItem>
    on_release: self.show_info_dialog()

<Content>
    orientation: "vertical"
    spacing: "12dp"
    size_hint_y: None
    height: "300dp"
    text: note_text.text

    ScrollView:

        MDGridLayout:
            id: grid
            cols: 1
            adaptive_height: True
            padding: dp(4), dp(4)
            spacing: dp(4)
            md_bg_color: app.theme_cls.bg_dark

            MDTextField:
                id: note_text
                multiline: True
                hint_text: "Enter notes here!"
                color_mode: 'accent'

<NoteItem>
    on_release: self.add_note_dialog() if self.secondary_text == 'Add your own notes here' else self.view_note_dialog()
