#:kivy 2.1.0
<PageGridLayout@GridLayout>
    background_color: (180/255,180/255,180/255,1)
    padding: 10,10
    spacing: 2,2
    canvas.before:
        Color:
            rgba: root.background_color
        Rectangle:
            size: self.size
            pos: self.pos

<DisplayAreaLayout@GridLayout>
    canvas.before:
        Rectangle:
            pos: self.pos
            size: self.size
            source: 'glassdisplay.png'

<DisplayLabel@Label>
    background_color: (1,1,1,0)
    text_size: root.width, root.height
    size: self.texture_size
    padding: 15,5
    font_size: (root.height * 0.8)
    valign: "bottom"
    halign: "right"

<DisplayTopLabel@Label>
    background_color: (1,1,1,0)
    text_size: root.width, root.height
    size: self.texture_size
    color: 0.8, 0.8, 0.8, 1
    padding: 15,5
    font_size: (root.height * 0.7)
    valign: "top"
    halign: "left"

<Button>
    font_size: (root.height * 0.45)

<ColouredButton@Button>
    background_color: (0,1,1,1)

<MainScreen>:
    PageGridLayout:
        cols: 1
        GridLayout:
            cols: 1
            padding: 5, 10
            size_hint_y: 0.2
            DisplayAreaLayout:
                cols: 1
                DisplayTopLabel:
                    id: display_top
                    text: ""
                    size_hint_y: 0.5
                DisplayLabel:
                    id: display
                    text: "0"
            Label:
                id: spacer
                size_hint_y: 0.2
        GridLayout:
            cols: 1
            spacing: 2,2
            size_hint_y: 0.7
            GridLayout:
                cols: 2
                size_hint_y: 0.16666
                Button:
                    text: "Clear"
                    size_hint_x: 0.7
                    on_release: root.clear_all()
                Button:
                    text: "Del"
                    size_hint_x: 0.3
                    on_release: root.backspace()
            GridLayout:
                cols: 4
                size_hint_y: 0.5
                spacing: 2,2
                Button:
                    text:"7"
                    on_release: root.add_to_numstring("7")
                Button:
                    text:"8"
                    on_release: root.add_to_numstring("8")
                Button:
                    text:"9"
                    on_release: root.add_to_numstring("9")
                ColouredButton:
                    text:"+"
                    on_release: root.operator_clicked("+")
                Button:
                    text:"4"
                    on_release: root.add_to_numstring("4")
                Button:
                    text:"5"
                    on_release: root.add_to_numstring("5")
                Button:
                    text:"6"
                    on_release: root.add_to_numstring("6")
                ColouredButton:
                    text:"-"
                    on_release: root.operator_clicked("-")
                Button:
                    text:"1"
                    on_release: root.add_to_numstring("1")
                Button:
                    text:"2"
                    on_release: root.add_to_numstring("2")
                Button:
                    text:"3"
                    on_release: root.add_to_numstring("3")
                ColouredButton:
                    text:"x"
                    on_release: root.operator_clicked("*")
            GridLayout:
                cols: 3
                size_hint_y: 0.16666
                spacing: 2,0
                Button:
                    text:"0"
                    on_release: root.add_to_numstring("0")
                    size_hint_x: 0.5
                Button:
                    text:"."
                    on_release: root.add_to_numstring(".")
                    size_hint_x: 0.25
                ColouredButton:
                    text:"÷"
                    on_release: root.operator_clicked("/")
                    size_hint_x: 0.25
            GridLayout:
                cols: 1
                size_hint_y: 0.16666
                spacing: 2,2
                padding: 2,2
                ColouredButton:
                    text: " = "
                    on_release: root.equals_clicked()
        Label:
            id: spacer
            size_hint_y: 0.05


<RootWidget>:
    MainScreen:
        name: "main_screen"